substitutions:
  name: atorch-dc-meter
  device0: meter0
  device1: meter1
  external_components_source: github://syssi/esphome-atorch-dl24@main
  dl24_mac_address0: !secret dl24_mac_address0
  dl24_mac_address1: !secret dl24_mac_address1
  project_version: 2.4.0
  device_description: "Monitor and control two Atorch meters via bluetooth"

esphome:
  name: ${name}
  friendly_name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-atorch-dl24"
    version: ${project_version}
  devices:
    - id: device0
      name: "${device0}"
    - id: device1
      name: "${device1}"

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - switch.turn_off: ble_client_switch1
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${dl24_mac_address0}
    id: client0
  - mac_address: ${dl24_mac_address1}
    id: client1

atorch_dl24:
  - id: atorch0
    ble_client_id: client0
    check_crc: true
    # The meter publishes a status report per second via BLE notification. If you don't like this update interval
    # you can use this setting to throttle the sensor updates by skipping some status reports.
    throttle: 2s

  - id: atorch1
    ble_client_id: client1
    check_crc: true
    # The meter publishes a status report per second via BLE notification. If you don't like this update interval
    # you can use this setting to throttle the sensor updates by skipping some status reports.
    throttle: 2s

binary_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    running:
      name: "running"
      device_id: device0

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    running:
      name: "running"
      device_id: device1

button:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    reset_energy:
      name: "reset energy"
      device_id: device0
    reset_capacity:
      name: "reset capacity"
      device_id: device0
    reset_runtime:
      name: "reset runtime"
      device_id: device0
    reset_all:
      name: "reset all"
      device_id: device0
    usb_plus:
      name: "plus"
      device_id: device0
    usb_minus:
      name: "minus"
      device_id: device0
    setup:
      name: "setup"
      device_id: device0
    enter:
      name: "enter"
      device_id: device0

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    reset_energy:
      name: "reset energy"
      device_id: device1
    reset_capacity:
      name: "reset capacity"
      device_id: device1
    reset_runtime:
      name: "reset runtime"
      device_id: device1
    reset_all:
      name: "reset all"
      device_id: device1
    usb_plus:
      name: "plus"
      device_id: device1
    usb_minus:
      name: "minus"
      device_id: device1
    setup:
      name: "setup"
      device_id: device1
    enter:
      name: "enter"
      device_id: device1

sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    voltage:
      name: "voltage"
      device_id: device0
    current:
      name: "current"
      device_id: device0
    power:
      name: "power"
      device_id: device0
    capacity:
      name: "capacity"
      device_id: device0
    energy:
      name: "energy"
      device_id: device0
    temperature:
      name: "temperature"
      device_id: device0
    dim_backlight:
      name: "dim backlight"
      device_id: device0
    runtime:
      name: "runtime"
      device_id: device0

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    voltage:
      name: "voltage"
      device_id: device1
    current:
      name: "current"
      device_id: device1
    power:
      name: "power"
      device_id: device1
    capacity:
      name: "capacity"
      device_id: device1
    energy:
      name: "energy"
      device_id: device1
    temperature:
      name: "temperature"
      device_id: device1
    dim_backlight:
      name: "dim backlight"
      device_id: device1
    runtime:
      name: "runtime"
      device_id: device1

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "enable bluetooth connection"
    id: ble_client_switch0
    device_id: device0

  - platform: ble_client
    ble_client_id: client1
    name: "enable bluetooth connection"
    id: ble_client_switch1
    device_id: device1

text_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    runtime_formatted:
      name: "runtime formatted"
      device_id: device0

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    runtime_formatted:
      name: "runtime formatted"
      device_id: device1
