substitutions:
  name: atorch-dc-meter
  device0: meter0
  device1: meter1
  external_components_source: github://syssi/esphome-atorch-dl24@main
  dl24_mac_address0: !secret dl24_mac_address0
  dl24_mac_address1: !secret dl24_mac_address1
  project_version: 2.1.0
  device_description: "Monitor and control two Atorch meters via bluetooth"

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-atorch-dl24"
    version: ${project_version}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

esp32_ble_tracker:

ble_client:
  - mac_address: ${dl24_mac_address0}
    id: ble_client0
  - mac_address: ${dl24_mac_address1}
    id: ble_client1

atorch_dl24:
  - id: atorch0
    ble_client_id: ble_client0
    check_crc: true
    # The meter publishes a status report per second via BLE notification. If you don't like this update interval
    # you can use this setting to throttle the sensor updates by skipping some status reports.
    throttle: 2s

  - id: atorch1
    ble_client_id: ble_client1
    check_crc: true
    # The meter publishes a status report per second via BLE notification. If you don't like this update interval
    # you can use this setting to throttle the sensor updates by skipping some status reports.
    throttle: 2s

binary_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    running:
      name: "${device0} running"

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    running:
      name: "${device1} running"

sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    voltage:
      name: "${device0} voltage"
    current:
      name: "${device0} current"
    power:
      name: "${device0} power"
    capacity:
      name: "${device0} capacity"
    energy:
      name: "${device0} energy"
    temperature:
      name: "${device0} temperature"
    dim_backlight:
      name: "${device0} dim backlight"
    runtime:
      name: "${device0} runtime"

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    voltage:
      name: "${device1} voltage"
    current:
      name: "${device1} current"
    power:
      name: "${device1} power"
    capacity:
      name: "${device1} capacity"
    energy:
      name: "${device1} energy"
    temperature:
      name: "${device1} temperature"
    dim_backlight:
      name: "${device1} dim backlight"
    runtime:
      name: "${device1} runtime"

text_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    runtime_formatted:
      name: "${device0} runtime formatted"

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    runtime_formatted:
      name: "${device1} runtime formatted"

button:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    reset_energy:
      name: "${device0} reset energy"
    reset_capacity:
      name: "${device0} reset capacity"
    reset_runtime:
      name: "${device0} reset runtime"
    reset_all:
      name: "${device0} reset all"
    usb_plus:
      name: "${device0} plus"
    usb_minus:
      name: "${device0} minus"
    setup:
      name: "${device0} setup"
    enter:
      name: "${device0} enter"

  - platform: atorch_dl24
    atorch_dl24_id: atorch1
    reset_energy:
      name: "${device1} reset energy"
    reset_capacity:
      name: "${device1} reset capacity"
    reset_runtime:
      name: "${device1} reset runtime"
    reset_all:
      name: "${device1} reset all"
    usb_plus:
      name: "${device1} plus"
    usb_minus:
      name: "${device1} minus"
    setup:
      name: "${device1} setup"
    enter:
      name: "${device1} enter"
